name: Reema
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
style: taylor
title: Reema
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#2b2422"
    - "#cbd9e0"
    - "#45677a"
    - "#9c3627"
    - "#c38b73"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
